# Generated by Django 2.1.7 on 2019-03-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_card', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lastname1', models.CharField(max_length=25)),
                ('lastname2', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('cc_number', models.PositiveIntegerField(default=0)),
                ('exp_date', models.CharField(max_length=4)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ispservice.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=0)),
                ('i_speed', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ispservice.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ispservice.Plan'),
        ),
    ]
