# Generated by Django 2.1.7 on 2019-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispservice', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id_contract',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
