# Generated by Django 2.1.7 on 2019-03-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispservice', '0004_auto_20190320_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cc_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
