# Generated by Django 2.1.7 on 2019-03-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispservice', '0005_auto_20190320_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvc',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
