# Generated by Django 2.1.7 on 2019-03-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispservice', '0009_auto_20190321_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
